name: deployment_aml
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6
- nb_conda
- tornado
- cudatoolkit==9.0
- tensorflow-gpu==1.14.0
- pandas==0.25.3
- urllib3
- pip:
    # Required packages for AzureML execution, history, and data preparation.
  - papermill==1.1.0
  - python-dotenv==0.10.3
  - Pillow==6.1.0
  - wget==3.2
  - matplotlib==3.1.1
  - toolz==0.9.0
  - tqdm==4.32.2
  - azure-cli==2.0.63
  - azure-core
  - keras==2.2.0
  - azureml-core==1.0.57
  - azureml-contrib-services==1.0.57
  - locustio==0.11.0
  - prompt-toolkit==2.0.9
  - git+https://github.com/microsoft/AI-Utilities.git
  - PyOpenSSL
